name: Marshall-Moore_families
favicon: null
layout_spectrum: 0.3156953528523445
typography_spectrum: 0.710195860825479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3865898868534714
  lightness: 0.2003256599418819
  saturation: 0.5073264345992357
  rhythmicContrast: 0.391309606609866
purpose: []
