name: Marshall-Moore Families
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61214
title: MARSHALL MOORE FAMILIES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#552200'
    - '#005544'
    - '#80b3ff'
    - '#ff7315'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
