typography_spectrum: 0.61571
color:
  brandColors:
    - '#ffffff'
    - '#552200'
    - '#005544'
    - '#80b3ff'
    - '#ff7315'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Marshall-Moore Families
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: MARSHALL MOORE FAMILIES
description: The Official Site Of The Marshall & Moore Families
purpose: []
